package com.lin.webservice.service.test1;

import javax.jws.HandlerChain;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "MyTestService", targetNamespace = "http://test1.service.webservice.lin.com/")
@HandlerChain(file = "handler-chain.xml")
public interface MyTestService {


    /**
     * 
     * @param b
     * @param a
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(name = "addResult", targetNamespace = "")
    @RequestWrapper(localName = "add", targetNamespace = "http://test1.service.webservice.lin.com/")
    @ResponseWrapper(localName = "addResponse", targetNamespace = "http://test1.service.webservice.lin.com/")
    public int add(
        @WebParam(name = "a", targetNamespace = "")
        int a,
        @WebParam(name = "b", targetNamespace = "")
        int b, 
        @WebParam(name = "license", header = true)
        String license);

    /**
     * 
     * @param num2
     * @param num1
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(name = "divideResult", targetNamespace = "")
    @RequestWrapper(localName = "divide", targetNamespace = "http://test1.service.webservice.lin.com/")
    @ResponseWrapper(localName = "divideResponse", targetNamespace = "http://test1.service.webservice.lin.com/")
    public int divide(
        @WebParam(name = "num1", targetNamespace = "")
        int num1,
        @WebParam(name = "num2", targetNamespace = "")
        int num2);

}
