
package com.lin.umws.service;

import java.util.List;
import javax.activation.DataHandler;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IUserService", targetNamespace = "http://service.umws.lin.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IUserService {


    /**
     * 
     * @param user
     */
    @WebMethod
    @RequestWrapper(localName = "add", targetNamespace = "http://service.umws.lin.com/", className = "com.lin.umws.service.UserType")
    @ResponseWrapper(localName = "addResponse", targetNamespace = "http://service.umws.lin.com/", className = "com.lin.umws.service.AddResponseType")
    public void add(
        @WebParam(name = "user", targetNamespace = "http://service.umws.lin.com/")
        User user);

    /**
     * 
     * @param user
     */
    @WebMethod
    @RequestWrapper(localName = "delete", targetNamespace = "http://service.umws.lin.com/", className = "com.lin.umws.service.DeleteType")
    @ResponseWrapper(localName = "deleteResponse", targetNamespace = "http://service.umws.lin.com/", className = "com.lin.umws.service.DeleteResponseType")
    public void delete(
        @WebParam(name = "user", targetNamespace = "http://service.umws.lin.com/")
        User user);

    /**
     * 
     * @return
     *     returns java.util.List<com.lin.umws.service.User>
     */
    @WebMethod
    @WebResult(name = "user", targetNamespace = "http://service.umws.lin.com/")
    @RequestWrapper(localName = "list", targetNamespace = "http://service.umws.lin.com/", className = "com.lin.umws.service.ListType")
    @ResponseWrapper(localName = "listResponse", targetNamespace = "http://service.umws.lin.com/", className = "com.lin.umws.service.ListResponseType")
    public List<User> list();

    /**
     * 
     * @param password
     * @param username
     * @return
     *     returns com.lin.umws.service.User
     * @throws UserException_Exception
     */
    @WebMethod
    @WebResult(name = "user", targetNamespace = "http://service.umws.lin.com/")
    @RequestWrapper(localName = "login", targetNamespace = "http://service.umws.lin.com/", className = "com.lin.umws.service.LoginType")
    @ResponseWrapper(localName = "loginResponse", targetNamespace = "http://service.umws.lin.com/", className = "com.lin.umws.service.LoginResponseType")
    public User login(
        @WebParam(name = "username", targetNamespace = "http://service.umws.lin.com/")
        String username,
        @WebParam(name = "password", targetNamespace = "http://service.umws.lin.com/")
        String password)
        throws UserException_Exception
    ;

    /**
     * 
     * @param file
     */
    @WebMethod
    @RequestWrapper(localName = "badUpload", targetNamespace = "http://service.umws.lin.com/", className = "com.lin.umws.service.BadUploadType")
    @ResponseWrapper(localName = "badUploadResponse", targetNamespace = "http://service.umws.lin.com/", className = "com.lin.umws.service.EmptyType")
    public void badUpload(
        @WebParam(name = "file", targetNamespace = "http://service.umws.lin.com/")
        byte[] file);

    /**
     * 
     * @param mtomFile
     */
    @WebMethod
    @RequestWrapper(localName = "mtomUpload", targetNamespace = "http://service.umws.lin.com/", className = "com.lin.umws.service.MtomUploadType")
    @ResponseWrapper(localName = "mtomUploadResponse", targetNamespace = "http://service.umws.lin.com/", className = "com.lin.umws.service.EmptyType")
    public void mtomUpload(
        @WebParam(name = "mtomFile", targetNamespace = "http://service.umws.lin.com/")
        byte[] mtomFile);

    /**
     * 
     * @param handlerFile
     */
    @WebMethod
    @RequestWrapper(localName = "handlerUpload", targetNamespace = "http://service.umws.lin.com/", className = "com.lin.umws.service.HandlerUploadType")
    @ResponseWrapper(localName = "handlerUploadResponse", targetNamespace = "http://service.umws.lin.com/", className = "com.lin.umws.service.EmptyType")
    public void handlerUpload(
        @WebParam(name = "handlerFile", targetNamespace = "http://service.umws.lin.com/")
        DataHandler handlerFile);

}
