package com.lin.umws.service.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.4 2015-11-25T16:28:33.154+08:00
 * Generated source version: 3.1.4
 * 
 */
@WebService(targetNamespace = "http://service.umws.lin.com/", name = "IUserService")
@XmlSeeAlso({ ObjectFactory.class })
public interface IUserService {
	
	@RequestWrapper(localName = "handlerUpload", targetNamespace = "http://service.umws.lin.com/", className = "com.lin.umws.service.HandlerUploadType")
	@WebMethod
	@ResponseWrapper(localName = "handlerUploadResponse", targetNamespace = "http://service.umws.lin.com/", className = "com.lin.umws.service.EmptyType")
	public void handlerUpload(@WebParam(name = "handlerFile", targetNamespace = "http://service.umws.lin.com/") javax.activation.DataHandler handlerFile);
	
	@RequestWrapper(localName = "mtomUpload", targetNamespace = "http://service.umws.lin.com/", className = "com.lin.umws.service.MtomUploadType")
	@WebMethod
	@ResponseWrapper(localName = "mtomUploadResponse", targetNamespace = "http://service.umws.lin.com/", className = "com.lin.umws.service.EmptyType")
	public void mtomUpload(@WebParam(name = "mtomFile", targetNamespace = "http://service.umws.lin.com/") byte[] mtomFile);
	
	@WebResult(name = "user", targetNamespace = "http://service.umws.lin.com/")
	@RequestWrapper(localName = "login", targetNamespace = "http://service.umws.lin.com/", className = "com.lin.umws.service.LoginType")
	@WebMethod
	@ResponseWrapper(localName = "loginResponse", targetNamespace = "http://service.umws.lin.com/", className = "com.lin.umws.service.LoginResponseType")
	public com.lin.umws.service.client.User login(@WebParam(name = "username", targetNamespace = "http://service.umws.lin.com/") java.lang.String username,
			@WebParam(name = "password", targetNamespace = "http://service.umws.lin.com/") java.lang.String password) throws UserException_Exception;
	
	@RequestWrapper(localName = "badUpload", targetNamespace = "http://service.umws.lin.com/", className = "com.lin.umws.service.BadUploadType")
	@WebMethod
	@ResponseWrapper(localName = "badUploadResponse", targetNamespace = "http://service.umws.lin.com/", className = "com.lin.umws.service.EmptyType")
	public void badUpload(@WebParam(name = "file", targetNamespace = "http://service.umws.lin.com/") byte[] file);
	
	public void add(@WebParam(name = "user", targetNamespace = "http://service.umws.lin.com/") com.lin.umws.service.client.User user);
	
	@WebResult(name = "user", targetNamespace = "http://service.umws.lin.com/")
	@RequestWrapper(localName = "list", targetNamespace = "http://service.umws.lin.com/", className = "com.lin.umws.service.ListType")
	@WebMethod
	@ResponseWrapper(localName = "listResponse", targetNamespace = "http://service.umws.lin.com/", className = "com.lin.umws.service.ListResponseType")
	public java.util.List<com.lin.umws.service.client.User> list();
	
	@RequestWrapper(localName = "delete", targetNamespace = "http://service.umws.lin.com/", className = "com.lin.umws.service.DeleteType")
	@WebMethod
	@ResponseWrapper(localName = "deleteResponse", targetNamespace = "http://service.umws.lin.com/", className = "com.lin.umws.service.DeleteResponseType")
	public void delete(@WebParam(name = "user", targetNamespace = "http://service.umws.lin.com/") com.lin.umws.service.client.User user);
}
