package com.lin.umws.service.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.4
 * 2015-11-25T16:28:33.162+08:00
 * Generated source version: 3.1.4
 * 
 */
@WebServiceClient(name = "UserService", 
                  wsdlLocation = "file:/usr/local/codes/git/webservice/ws-modules/cxf-server/src/test/resources/wsdl/user-doc.wsdl",
                  targetNamespace = "http://service.umws.lin.com/") 
public class UserService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://service.umws.lin.com/", "UserService");
    public final static QName UserServicePort = new QName("http://service.umws.lin.com/", "UserServicePort");
    static {
        URL url = null;
        try {
            url = new URL("file:/usr/local/codes/git/webservice/ws-modules/cxf-server/src/test/resources/wsdl/user-doc.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(UserService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/usr/local/codes/git/webservice/ws-modules/cxf-server/src/test/resources/wsdl/user-doc.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public UserService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public UserService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public UserService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public UserService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public UserService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public UserService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns IUserService
     */
    @WebEndpoint(name = "UserServicePort")
    public IUserService getUserServicePort() {
        return super.getPort(UserServicePort, IUserService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IUserService
     */
    @WebEndpoint(name = "UserServicePort")
    public IUserService getUserServicePort(WebServiceFeature... features) {
        return super.getPort(UserServicePort, IUserService.class, features);
    }

}
