
package com.lin.umws.service.client;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.4
 * 2015-11-25T16:28:33.145+08:00
 * Generated source version: 3.1.4
 */

@WebFault(name = "UserException", targetNamespace = "http://service.umws.lin.com/")
public class UserException_Exception extends Exception {
    
    private com.lin.umws.service.client.UserException userException;

    public UserException_Exception() {
        super();
    }
    
    public UserException_Exception(String message) {
        super(message);
    }
    
    public UserException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public UserException_Exception(String message, com.lin.umws.service.client.UserException userException) {
        super(message);
        this.userException = userException;
    }

    public UserException_Exception(String message, com.lin.umws.service.client.UserException userException, Throwable cause) {
        super(message, cause);
        this.userException = userException;
    }

    public com.lin.umws.service.client.UserException getFaultInfo() {
        return this.userException;
    }
}
