
package com.lin.umws.service;

import java.util.List;

import javax.activation.DataHandler;
import javax.jws.HandlerChain;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlMimeType;
import javax.xml.ws.BindingType;
import javax.xml.ws.soap.MTOM;
import javax.xml.ws.soap.SOAPBinding;

import com.lin.umws.entity.User;
import com.lin.umws.exception.UserException;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IUserService", targetNamespace = "http://service.umws.lin.com/")
//@HandlerChain(file = "handler-chain.xml")
@BindingType(SOAPBinding.SOAP12HTTP_MTOM_BINDING)
public interface IUserService {


    /**
     * 
     * @param user
     */
    @WebMethod
    public void add(
        @WebParam(name = "user", targetNamespace = "http://service.umws.lin.com/")
        User user);

    /**
     * 
     * @param user
     */
    @WebMethod
    public void delete(
        @WebParam(name = "user", targetNamespace = "http://service.umws.lin.com/")
        User user);

    /**
     * 
     * @return
     *     returns java.util.List<com.lin.umws.service.User>
     */
    @WebMethod
    @WebResult(name = "user", targetNamespace = "http://service.umws.lin.com/")
    public List<User> list();

    /**
     * 
     * @param password
     * @param username
     * @return
     *     returns com.lin.umws.service.User
     * @throws UserException_Exception
     */
    @WebMethod
    @WebResult(name = "user", targetNamespace = "http://service.umws.lin.com/")
    public User login(
        @WebParam(name = "username", targetNamespace = "http://service.umws.lin.com/")
        String username,
        @WebParam(name = "password", targetNamespace = "http://service.umws.lin.com/")
        String password)
        throws UserException;
    
    /**
     * 
     * @param file
     */
    @WebMethod
    public void badUpload(
        @WebParam(name = "file", targetNamespace = "http://service.umws.lin.com/")
        byte[] file);
    
    /**
     * 
     * @param file
     */
    @WebMethod
    @MTOM
    public void mtomUpload(
        @WebParam(name = "mtomFile", targetNamespace = "http://service.umws.lin.com/")
        byte[] mtomFile);
    
    /**
     * 
     * desc: TODO
     * @param handler
     */
    @WebMethod
    public void handlerUpload(
    		@WebParam(name = "handlerFile", targetNamespace = "http://service.umws.lin.com/")
    		@XmlMimeType("application/octet-stream")
            DataHandler handler);

}
